// Utility helpers for legacy itinerary HTML rendering

/**
 * Older saved trips store an HTML version of the itinerary that already includes a big
 * gradient "Header" section. Our UI also renders its own header (image + map), so we
 * strip the embedded header to avoid duplicate headers.
 */
export const stripGeneratedItineraryHeader = (html: string): string => {
  if (!html) return html;

  try {
    // DOMParser is available in the browser; this function is only used client-side.
    const doc = new DOMParser().parseFromString(html, "text/html");

    // Match only the top header block generated by generateItineraryHtml (ChatPage)
    // and avoid touching other gradient blocks like day headers.
    const header = doc.body.querySelector(
      'div[style*="linear-gradient(135deg, #667eea"][style*="padding: 24px"][style*="border-radius: 16px"][style*="margin-bottom: 24px"]'
    );

    if (header) header.remove();

    const cleaned = doc.body.innerHTML;
    return cleaned && cleaned.trim().length > 0 ? cleaned : html;
  } catch {
    return html;
  }
};
