// This file is automatically generated. Do not edit it directly.
// (Parche temporal: eliminado el uso de ./types porque el archivo no se generó)

import { createClient, SupabaseClient } from "@supabase/supabase-js";

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) || "";
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) || "";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase URL or Publishable Key is missing. Please check your environment variables (VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient = createClient(
  SUPABASE_URL || "https://ecgyhfdzpuypjqirtsmi.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "sb_publishable_KKmb4GcJc4MnzMVi6jE9sQ_lR58_L-P",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
